# Generated by Django 2.0.3 on 2018-03-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compress_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(max_length=250)),
                ('options', models.CharField(max_length=250)),
            ],
        ),
    ]
