# Generated by Django 2.0.3 on 2018-03-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compress_file',
            old_name='str_name',
            new_name='name',
        ),
    ]
